### ISSUE TITLE
front-end login/signup

### ISSUE THREAD

**Issue by jeffcousins** [HR10Knights/HR10Knights#13]
basics

**Comment by apedley** [comment]
I plan on doing the backend like this:

https://vickev.com/#!/article/authentication-in-single-page-applications-node-js-passportjs-angularjs

But using /api/login /api/logout and /api/signup for the routes.

**Comment by apedley** [comment]
Also we need a space for team name.. maybe do it like Slack where the user puts in a team name and that verifies before we have them sign up? If so, let me know and I'll write a function to verify team name

**Comment by jeffcousins** [comment]
Looks great!
